# Lightweight and flexible command-line JSON processor
brew "jq"
# Cross-shell prompt for astronauts
brew "starship"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# UNIX shell (command interpreter)
brew "zsh"
# Application uninstaller
cask "appcleaner"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-sauce-code-pro-nerd-font"
# Web browser
cask "google-chrome"
# Team communication and collaboration software
cask "slack"
# Open-source code editor
cask "visual-studio-code"
