# Official Amazon AWS command-line interface
brew "awscli"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Cross-shell prompt for astronauts
brew "starship"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# UNIX shell (command interpreter)
brew "zsh"
# Application uninstaller
cask "appcleaner"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-sauce-code-pro-nerd-font"
# Web browser
cask "google-chrome"
# Team communication and collaboration software
cask "slack"
# Native GUI tool for relational databases
cask "tableplus"
# Open-source code editor
cask "visual-studio-code"
