# Homebrewの設定
eval "$(/opt/homebrew/bin/brew shellenv zsh)"
export HOMEBREW_BUNDLE_FILE="$HOME/.Brewfile"
export HOMEBREW_BUNDLE_DESCRIBE=true
export HOMEBREW_BUNDLE_DUMP_NO_VSCODE=true

# # Starshipの設定
# eval "$(starship init zsh)"

# # voltaの設定
# VOLTA_HOME="$HOME/.volta"
# PATH="$VOLTA_HOME/bin:$PATH"
